name: CD

on:
  push:
  # workflow_dispatch:
  # workflow_run:
  #   workflows: ["CI"]
  #   types:
  #     - completed

jobs:
  vercel:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: checkout setup
        uses: actions/setup-node@v1

      - name: deploy to vercel
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi

          npx vercel --token ${VERCEL_TOKEN} $prodRun -m githubCommitAuthor=${{ github.actor }} githubDeployment=1 githubCommitRef=${{ github.ref_name }} githubRepo=${{ github.repository }} githubOrg=${{ github.repository_owner }} githubCommitOrg=${{ github.repository_owner }} githubCommitRepo=${{ github.repository }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
