name: CD

on:
  push:
  # workflow_dispatch:
  # workflow_run:
  #   workflows: ["CI"]
  #   types:
  #     - completed

jobs:
  vercel:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: checkout setup
        uses: actions/setup-node@v1

      - name: deploy to vercel
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi

          npx vercel --token ${VERCEL_TOKEN} $prodRun -m githubCommitSha=${{ github.sha }} -m githubCommitAuthor=${{ github.actor }} -m githubDeployment=1 -m githubCommitRef=${{ github.ref_name }}  -m githubRepo=${{ github.repository }} -m githubOrg=${{ github.repository_owner }} -m githubCommitOrg=${{ github.repository_owner }} -m githubCommitRepo="${{ github.repository }} -m githubCommitMessage="${{ github.event.head_commit.message }}"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
