name: ci/cd

on:
  [push]
  # the `github.event.head_commit.message` is only valid on push
  # push:
  #   branches:
  #     - main
  # pull_request:

jobs:
  main:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: checkout setup
        uses: actions/setup-node@v2

      - name: cache deps
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: install deps
        run: npm ci

      - name: check typescript
        run: npm run tsc

      - name: check lint
        run: npm run lint

      - name: check format
        run: npm run format

  vercel:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: main

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: checkout setup
        uses: actions/setup-node@v1

      - name: deploy to vercel
        id: deploy-vercel
        uses: andyrichardson/vercel-action@v21 # See ISSUE comment: https://github.com/amondnet/vercel-action/issues/78#issuecomment-940843410
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required

    outputs:
      link: ${{ steps.deploy-vercel.outputs.preview-url }}

  monitor:
    name: lighthouse
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: vercel

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: audit URL
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            ${{ needs.vercel.outputs.link }}
          uploadArtifacts: true # save results as an action artifacts
